version: '3'

services:
  database:
    image: mysql:5.7.22
    container_name: database
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    env_file: .env
    # Specify character set for table creation
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

volumes:
  my-db:

